//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleForEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int TourId { get; set; }
        public string TourName { get; set; }
        public Nullable<bool> SeniorDiscountAvailable { get; set; }
        public Nullable<bool> KidFriendly { get; set; }
        public Nullable<bool> MultiDay { get; set; }
        public string Region { get; set; }
        public Nullable<int> MaxPeoplePerTour { get; set; }
        public string TourImagePath { get; set; }
        public string Description { get; set; }
    }
}
